In [11]:
import pandas as pd
pd.DataFrame({"Bob":["He is Fat","He is 21 years old"],"Sue":["He is slim","He is 20 years old"]},index=["Person 1","Person 2"])
print()
pd.Series([30,23,40,53],index=["Sales of 2025", "Sales of 2024","Sales of 2023","Sales of 2022"], name="Product")

Sales of 2025    30
Sales of 2024    23
Sales of 2023    40
Sales of 2022    53
Name: Product, dtype: int64

In [49]:
import pandas as pd
df=pd.read_csv('students.csv')
print(df)
df=df.set_index("city")
print(df)

    name  age  marks       city
0   Asha   16     92      Kochi
1  Rahul   17     88      Delhi
2  Meera   16     95  Bengaluru
3  Arjun   18     79    Chennai
4   Diya   17     85     Mumbai
            name  age  marks
city
Kochi       Asha   16     92
Delhi      Rahul   17     88
Bengaluru  Meera   16     95
Chennai    Arjun   18     79
Mumbai      Diya   17     85

In [21]:
import numpy as pandas
pd.DataFrame({"Apples":['30'],"Banana":['21']})

  Apples Banana
0     30     21

In [92]:
import pandas as pd
df=pd.read_csv("students.csv")
print(df)
print()
# print(df["marks"]>90)
# print()
# print(df[df["marks"]>90])


print(df.marks>90)
print()
print(df[df.marks>90])

# print((df["city"]=="Delhi") | (df['marks']>90))
# print()
# print((df[df.city=="Delhi"]))

# print(df[df["city"].isin(["Delhi","Mumbai"])])

    name  age  marks       city
0   Asha   16     92      Kochi
1  Rahul   17     88      Delhi
2  Meera   16     95  Bengaluru
3  Arjun   18     79    Chennai
4   Diya   17     85     Mumbai

0     True
1    False
2     True
3    False
4    False
Name: marks, dtype: bool

    name  age  marks       city
0   Asha   16     92      Kochi
2  Meera   16     95  Bengaluru

In [ ]:
import numpy as np
import pandas as pd
df=pd.DataFrame({"Name":["Luffy","Zoro","Sanji"],"Age":[16,np.nan,20]})
print(df)
print()
print(df.isnull())
print([df["Age"].isnull(])
print()
print(df.notnull())

    Name   Age
0  Luffy  16.0
1   Zoro   NaN
2  Sanji  20.0

    Name    Age
0  False  False
1  False   True
2  False  False

   Name    Age
0  True   True
1  True  False
2  True   True

In [91]:
import pandas as pd
df=pd.DataFrame({"Name":["Luffy","Zoro","Sanji"],"Age":[16,17,18]})
df["Place"]=["North blue","south blue","All blue"]
df["mark"]=range(3,0,-1)
print(df)

    Name  Age       Place  mark
0  Luffy   16  North blue     3
1   Zoro   17  south blue     2
2  Sanji   18    All blue     1

In [118]:
import pandas as pd
data=pd.DataFrame({'Name':["Luffy","Zoro","Luffy","Zoro","Luffy","Zoro"],"Place":["South blue","South blue","North blue","North blue","All blue","All blue"],"Marks":[80,70,60,50,40,30]})
print(data)
# data.groupby("Marks").Marks.count()
# data.groupby("Name").Marks.min()
# data.groupby('Name').apply(lambda des:des.Marks.iloc[0])
# data.groupby('Place').apply(lambda des:des.Marks.iloc[1])
# data.groupby("Name").Marks.max()
data.groupby("Name").Marks.agg([len,min,max])

    Name       Place  Marks
0  Luffy  South blue     80
1   Zoro  South blue     70
2  Luffy  North blue     60
3   Zoro  North blue     50
4  Luffy    All blue     40
5   Zoro    All blue     30

       len  min  max
Name
Luffy    3   40   80
Zoro     3   30   70